version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: deploy-task-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
      GF_PATHS_PROVISIONING: 	/etc/grafana/provisioning
    ports:
      - 80:3000
    volumes:
      - ./grafana:/etc/grafana
      - grafana-data:/var/lib/grafana
    networks:
      - Bobkov-E-O-deploy-task
    restart: unless-stopped

  # postgres:
  #   image: postgres:13.3
  #   container_name: deploy-task-postgresql
  #   environment:
  #     POSTGRES_DB: "egordb"
  #     POSTGRES_USER: "egoruser"
  #     POSTGRES_PASSWORD: "12345678"
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - Bobkov-E-O-deploy-task
  #   restart: unless-stopped

volumes:
  grafana-data:

networks:
  Bobkov-E-O-deploy-task:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1