all:
  children:
    grafana-postgres:
      hosts:
        10.129.0.15: # Insert here host-ip for grafana+postgres containers
    nginx:
      hosts:
        10.129.0.22 # Insert here host-ip for nginx-proxy node
